import { describe, expect, it } from 'vitest';
import { analyzeTrace } from '../../src/capture/analyzer.js';
import { generateTestFile } from '../../src/capture/generator.js';
import type { ToolTrace } from '../../src/trace/types.js';

const trace: ToolTrace = {
  calls: [
    {
      toolName: 'read_file',
      args: { path: '/config.yaml' },
      result: { type: 'success', content: 'port: 3000' },
      durationMs: 10,
      sequenceIndex: 0,
      unknownTool: false,
    },
    {
      toolName: 'bash',
      args: { command: 'npm run build' },
      result: { type: 'success', content: 'ok' },
      durationMs: 500,
      sequenceIndex: 1,
      unknownTool: false,
    },
  ],
  totalCalls: 2,
  totalDurationMs: 510,
};

describe('generateTestFile', () => {
  it('generates valid test structure', () => {
    const analysis = analyzeTrace(trace, 'Build done.');
    const output = generateTestFile(analysis, {
      testName: 'deploy the app',
      skillPath: './SKILL.md',
      cassettePath: './cassettes/deploy.json',
    });

    expect(output).toContain('AUTO-GENERATED by tracepact capture');
    expect(output).toContain("import { expect, test } from 'vitest'");
    expect(output).toContain("import { runSkill, parseSkill } from '@tracepact/vitest'");
    expect(output).toContain("test('deploy the app'");
    expect(output).toContain("replay: './cassettes/deploy.json'");
    expect(output).toContain("parseSkill('./SKILL.md')");
  });

  it('includes tool call assertions', () => {
    const analysis = analyzeTrace(trace, 'Build done.');
    const output = generateTestFile(analysis, {
      testName: 'build',
      skillPath: './SKILL.md',
      cassettePath: './cassettes/build.json',
    });

    expect(output).toContain("toHaveCalledTool('read_file')");
    expect(output).toContain("toHaveCalledTool('bash')");
    expect(output).toContain('toHaveCalledToolsInOrder');
  });

  it('includes semantic assertion with --with-semantic', () => {
    const analysis = analyzeTrace(trace, 'Build completed successfully.');
    const output = generateTestFile(analysis, {
      testName: 'build',
      skillPath: './SKILL.md',
      cassettePath: './cassettes/build.json',
      withSemantic: true,
    });

    expect(output).toContain('toBeSemanticallySimilar');
    expect(output).toContain('Build completed successfully.');
  });

  it('omits semantic assertion without flag', () => {
    const analysis = analyzeTrace(trace, 'Build done.');
    const output = generateTestFile(analysis, {
      testName: 'build',
      skillPath: './SKILL.md',
      cassettePath: './cassettes/build.json',
      withSemantic: false,
    });

    expect(output).not.toContain('toBeSemanticallySimilar');
  });

  it('escapes special characters in strings', () => {
    const analysis = analyzeTrace(trace, "It's done\nsuccessfully");
    const output = generateTestFile(analysis, {
      testName: "test with 'quotes'",
      skillPath: './SKILL.md',
      cassettePath: './cassettes/test.json',
      withSemantic: true,
    });

    expect(output).toContain("test with \\'quotes\\'");
    expect(output).not.toContain("test with 'quotes'");
  });
});
