import type { InferredAssertion, TraceAnalysis } from './analyzer.js';

export interface GenerateOptions {
  testName: string;
  skillPath: string;
  cassettePath: string;
  withSemantic?: boolean;
}

export function generateTestFile(analysis: TraceAnalysis, options: GenerateOptions): string {
  const lines: string[] = [];

  // Header
  lines.push(`// AUTO-GENERATED by tracepact capture — ${new Date().toISOString().split('T')[0]}`);
  lines.push(`import { expect, test } from 'vitest';`);
  lines.push(`import { runSkill, parseSkill } from '@tracepact/vitest';`);
  lines.push('');

  // Test block
  lines.push(`test('${escapeString(options.testName)}', async () => {`);
  lines.push(`  const skill = await parseSkill('${escapeString(options.skillPath)}');`);
  lines.push('  const result = await runSkill(skill, {');
  lines.push(`    prompt: '${escapeString(options.testName)}',`);
  lines.push(`    replay: '${escapeString(options.cassettePath)}',`);
  lines.push('  });');
  lines.push('');

  // Tool call assertions
  lines.push('  // Tools called in the captured run:');
  for (const assertion of analysis.assertions) {
    const line = renderAssertion(assertion);
    if (line) lines.push(`  ${line}`);
  }

  // Semantic assertion on output
  if (options.withSemantic && analysis.output.length > 0) {
    lines.push('');
    lines.push('  // Output captured as semantic baseline:');
    const truncated =
      analysis.output.length > 200 ? analysis.output.slice(0, 200) : analysis.output;
    lines.push(`  expect(result).toBeSemanticallySimilar('${escapeString(truncated)}');`);
  }

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

function renderAssertion(assertion: InferredAssertion): string | null {
  switch (assertion.type) {
    case 'calledTool':
      return `expect(result).toHaveCalledTool('${escapeString(String(assertion.args[0]))}');`;

    case 'calledToolInOrder': {
      const tools = assertion.args[0] as string[];
      const formatted = tools.map((t) => `'${escapeString(t)}'`).join(', ');
      return `expect(result).toHaveCalledToolsInOrder([${formatted}]);`;
    }

    case 'calledToolWith': {
      const toolName = String(assertion.args[0]);
      const args = assertion.args[1] as Record<string, unknown>;
      const formatted = formatArgs(args);
      return `expect(result).toHaveCalledTool('${escapeString(toolName)}', ${formatted});`;
    }

    case 'semanticSimilar':
      return null;

    default:
      return null;
  }
}

function formatArgs(args: Record<string, unknown>): string {
  const entries: string[] = [];
  for (const [key, value] of Object.entries(args)) {
    if (value && typeof value === 'object' && '__pattern' in (value as any)) {
      const pattern = value as { __pattern: string; value: string };
      entries.push(`${key}: expect.stringContaining('${escapeString(pattern.value)}')`);
    } else if (typeof value === 'string') {
      entries.push(`${key}: '${escapeString(value)}'`);
    } else {
      entries.push(`${key}: ${JSON.stringify(value)}`);
    }
  }
  return `{ ${entries.join(', ')} }`;
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}
