import '@tracepact/vitest/setup';
import { parseSkill, runSkill } from '@tracepact/vitest';
// AUTO-GENERATED by tracepact capture — 2026-03-06
import { expect, test } from 'vitest';

test('deploy to staging', async () => {
  const skill = await parseSkill('./examples/agent-example/SKILL.md');
  const result = await runSkill(skill, {
    prompt: 'deploy to staging',
    replay: './examples/agent-example/cassettes/deploy-staging.json',
  });

  // Tools called in the captured run:
  expect(result.trace).toHaveCalledTool('read_file');
  expect(result.trace).toHaveCalledTool('bash');
  expect(result.trace).toHaveCalledTool('write_file');
  expect(result.trace).toHaveCalledToolsInOrder(['read_file', 'bash', 'write_file']);
});
