import type { ProviderInfo } from './types.js';

/**
 * Static fallback catalog for offline/first-run scenarios.
 * Only includes the most popular models per supported provider.
 * Updated: 2026-03-06
 */
export const SNAPSHOT_PROVIDERS: ProviderInfo[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    envKeys: ['ANTHROPIC_API_KEY'],
    api: 'https://api.anthropic.com/v1',
    models: [
      {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude 4.5 Sonnet',
        provider: 'anthropic',
        contextWindow: 200000,
        maxOutput: 8192,
        supportsTools: true,
        supportsReasoning: true,
        cost: { input: 3, output: 15 },
        tags: ['recommended'],
      },
      {
        id: 'claude-haiku-4-5-20251001',
        name: 'Claude Haiku 4.5',
        provider: 'anthropic',
        contextWindow: 200000,
        maxOutput: 8192,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 0.8, output: 4 },
        tags: ['fast', 'cheap'],
      },
      {
        id: 'claude-opus-4-6',
        name: 'Claude Opus 4.6',
        provider: 'anthropic',
        contextWindow: 200000,
        maxOutput: 16384,
        supportsTools: true,
        supportsReasoning: true,
        cost: { input: 15, output: 75 },
        tags: ['powerful'],
      },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    envKeys: ['OPENAI_API_KEY'],
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        provider: 'openai',
        contextWindow: 128000,
        maxOutput: 16384,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 2.5, output: 10 },
        tags: ['recommended'],
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o mini',
        provider: 'openai',
        contextWindow: 128000,
        maxOutput: 16384,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 0.15, output: 0.6 },
        tags: ['fast', 'cheap'],
      },
      {
        id: 'gpt-4.1',
        name: 'GPT-4.1',
        provider: 'openai',
        contextWindow: 1047576,
        maxOutput: 32768,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 2, output: 8 },
        tags: ['recommended'],
      },
      {
        id: 'gpt-4.1-mini',
        name: 'GPT-4.1 mini',
        provider: 'openai',
        contextWindow: 1047576,
        maxOutput: 32768,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 0.4, output: 1.6 },
        tags: ['fast', 'cheap'],
      },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    envKeys: ['GROQ_API_KEY'],
    api: 'https://api.groq.com/openai/v1',
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        provider: 'groq',
        contextWindow: 128000,
        maxOutput: 32768,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 0.59, output: 0.79 },
        tags: ['fast', 'cheap'],
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    envKeys: ['DEEPSEEK_API_KEY'],
    api: 'https://api.deepseek.com',
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek V3',
        provider: 'deepseek',
        contextWindow: 64000,
        maxOutput: 8192,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 0.27, output: 1.1 },
        tags: ['cheap'],
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1',
        provider: 'deepseek',
        contextWindow: 64000,
        maxOutput: 8192,
        supportsTools: true,
        supportsReasoning: true,
        cost: { input: 0.55, output: 2.19 },
        tags: ['reasoning'],
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    envKeys: ['MISTRAL_API_KEY'],
    api: 'https://api.mistral.ai/v1',
    models: [
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large',
        provider: 'mistral',
        contextWindow: 128000,
        maxOutput: 8192,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 2, output: 6 },
        tags: [],
      },
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    envKeys: ['XAI_API_KEY'],
    api: 'https://api.x.ai/v1',
    models: [
      {
        id: 'grok-3',
        name: 'Grok 3',
        provider: 'xai',
        contextWindow: 131072,
        maxOutput: 16384,
        supportsTools: true,
        supportsReasoning: false,
        cost: { input: 3, output: 15 },
        tags: [],
      },
    ],
  },
];
